# Everything in this section will be available as an environment variable
db_username = "Jane"
db_password = "mypassword"

client_id = "517222506229-vsmmajv00ul0bs7p89v5m89qs8eb9359.apps.googleusercontent.com"
client_secret= "RUP0RZ6e0pPhDzsqIJ7KlNd1"
refresh_token= "1//09asyTjAhD1BJCgYIARAAGAkSNwF-L9Ir8taawTvtFQMVWgu2rGunqDAo4I86q_3LNat9dCjMeorkQuBJdeHn5gDQxIdZmHZ6750"
# You can also add other sections if you like.
# The contents of sections as shown below will not become environment variables,
# but they'll be easily accessible from within Streamlit anyway as we show
# later in this doc.
[my_other_secrets]
things_i_like = ["Streamlit", "Python"]